#include "graphics.h"

#include "globals.h"
//char player1[] = "BBBRRRRRBBB BBR55555RBB BBR5B5B5RBB BBR55555RBB BBR5BBB5RBB BBBY555YBBB BB5YYYYY5BB BB5YYBYY5BB BB5YYYYY5BB BB5YYBYY5BB BBBYYYYYBBB";
//char player2[] = "BBBRRRRRBBB BBR55555RBB BBR5B5B5RBB BBR55555RBB BBR5BBB5RBB BB5Y555Y5BB BB5YYYYY5BB BB5YYBYY5BB BB5YYYYY5BB BBBYYBYYBBB BBBYYYYYBBB";
//char player1[] = "WBBRRRRRBBW BWR55555RWB BBW5B5B5WBB BBRW555WRBB BBR5WBW5RBB BBBY5W5YBBB BB5YWYWY5BB BB5WYBYW5BB BBWYYYYYWBB BW5YYBYY5WB WBBYYYYYBBW";
void draw_player(int u, int v, int key, int moved, int stuck)
{
    char player1[] = "BBBRRRRRBBBBBR55555RBBBBR5B5B5RBBBBR55555RBBBBR5BBB5RBBBBBY555YBBBBB5YYYYY5BBBB5YYBYY5BBBB5YYYYY5BBBB5YYBYY5BBBBBYYYYYBBB";
    char player2[] = "BBBRRRRRBBBBBR55555RBBBBR5B5B5RBBBBR55555RBBBBR5BBB5RBBBB5Y555Y5BBBB5YYYYY5BBBB5YYBYY5BBBB5YYYYY5BBBBBYYBYYBBBBBBYYYYYBBB";
    char players[] = "WBBRRRRRBBWBWR55555RWBBBW5B5B5WBBBBRW555WRBBBBR5WBW5RBBBBBY5W5YBBBBB5YWYWY5BBBB5WYBYW5BBBBWYYYYYWBBBW5YYBYY5WBWBBYYYYYBBW";
    if(stuck) {
        draw_img(u,v,players);
        return;
        }
    if(moved==1) {
        draw_img(u, v, player2);
        } else {
        draw_img(u, v, player1);
        }

}

#define YELLOW 0xFFFF00
#define BROWN  0xD2691E
#define DIRT   BROWN
#define BLUE    0x0000FF
#define WHITE   0xFFFFFF
void draw_img(int u, int v, const char* img)
{
    int colors[11*11];
    for (int i = 0; i < 11*11; i++)
    {
        if (img[i] == 'R')      colors[i] = RED;
        else if (img[i] == 'Y') colors[i] = YELLOW;
        else if (img[i] == 'G') colors[i] = GREEN;
        else if (img[i] == 'D') colors[i] = DIRT;
        else if (img[i] == '5') colors[i] = LGREY;
        else if (img[i] == '3') colors[i] = DGREY;
        else if (img[i] == 'L') colors[i] = BLUE;
        else if (img[i] == 'W') colors[i] = WHITE;
        else colors[i] = BLACK;
    }
    uLCD.BLIT(u, v, 11, 11, colors);
    wait_us(250); // Recovery time!
}

void draw_nothing(int u, int v)
{
    // Fill a tile with blackness
    uLCD.filled_rectangle(u, v, u+10, v+10, BLACK);
}

void draw_wall(int u, int v)
{
    uLCD.filled_rectangle(u, v, u+10, v+10, BROWN);
}

void draw_plant(int u, int v)
{
    char tree[]   = "BBBBGGGGBBBBBGGGGGGBBBBBGGGGGGBBBBGGGGGBBBBBBBBDGGBBBBBBDBDDBBBBBBBDDDDBDBBBBBBBDDDDBBBBBBBDDBBBBBBBBBDDBBBBBBBBDDDDBBBBB";
    draw_img(u, v, tree);
    //uLCD.filled_rectangle(u, v, u+10, v+10, GREEN);
}

void draw_thorn(int u, int  v)
{
    //char player1[] =  "BBBRRRRRBBB BBR55555RBB BBR5B5B5RBB BBR55555RBB BBR5BBB5RBB BBBY555YBBB BB5YYYYY5BB BB5YYBYY5BB BB5YYYYY5BB BB5YYBYY5BB BBBYYYYYBBB";
    //char thorn[] =    "BBBBBBBBBBB BBBBGGBBBBB BBBGDBBBBBB BBBBDGBGBBB GDGBDGDBBBB BGDDBDGGDGB BBGDDDBDDBB GDBBDDDDBGD BDDDDDGGGGG GDDDDDDDBBB BBBBBBBBBBB" "  
    //char pThorn[] =   "BBBRRRRRBBB BBR5GG55RBB BBRGD5B5RBB BBR5DG5GRBB GDG5DGD5RBB BGDD5DGGDGB BBGDDDYDDBB GD5YDDDD5GD BDDDDDGGGGG GDDDDDDD5BB BBBYYYYYBBB 
    char thorn[] = "BBBBBBBBBBBBBBBGGBBBBBBBBGDBBBBBBBBBBDGBGBBBGDGBDGDBBBBBGDDBDGGDGBBBGDDDBDDBBGDBBDDDDBGDBDDDDDGGGGGGBBBBBBBBBBBDDDDDDDBBB";

        draw_img(u, v, thorn);
    

}

void draw_mine(int u, int v)
{
    //char mine[] = "BBBBBBBBBBB BBBBBBBBBBB DDDDDDDDDDD DBDBDBDBDBD DDDDDDDDDDD BDD55555DDB BDD33335DDB BDD33335DDB BDD33335DDB BDD33335DDB BDD33335DDB"
    char mine[] = "BBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDBDBDBDBDBDDDDDDDDDDDDBDD55555DDBBDD33335DDBBDD33335DDBBDD33335DDBBDD33335DDBBDD33335DDB";
    draw_img(u, v, mine);
}

void draw_thornP(int u, int  v, int Player)
{
    //char player1[] =  "BBBRRRRRBBB BBR55555RBB BBR5B5B5RBB BBR55555RBB BBR5BBB5RBB BBBY555YBBB BB5YYYYY5BB BB5YYBYY5BB BB5YYYYY5BB BB5YYBYY5BB BBBYYYYYBBB";
    //char thorn[] =    "BBBBBBBBBBB BBBBGGBBBBB BBBGDBBBBBB BBBBDGBGBBB GDGBDGDBBBB BGDDBDGGDGB BBGDDDBDDBB GDBBDDDDBGD BDDDDDGGGGG GBBBBBBBBBB BDDDDDDDBBB" "  
    //char pThorn[] =   "BBBBBBBBBBB BBR5GG55RBB BBBGD5B5RBB BBR5DGBGBBB GDG5DGD5RBB BGDD5DGGDGB BBGDDDYDDBB GD5YDDDD5GD BDDDDDGGGGGG 
    char pThorn[] = "BBBRRRRRBBBBBR5GG55RBBBBRGD5B5RBBBBR5DG5GRBBGDG5DGD5RBBBGDD5DGGDGBBBGDDDYDDBBGD5YDDDD5GDBDDDDDGGGGGGDDDDDDD5BBBBBYYYYYBBB ";
        draw_img(u, v, pThorn);  

}

void draw_upper_status()
{
    // Draw bottom border of status bar
    uLCD.line(0, 9, 127, 9, GREEN);
    
    // Add other status info drawing code here
}

void draw_lower_status()
{
    // Draw top border of status bar
    uLCD.line(0, 118, 127, 118, GREEN);
    
    // Add other status info drawing code here
}
void draw_hearts(int health, int maxHealth) 
{
    char heart[] =     "BBBBBBBBBBBBBBBBBBBBBBBBRRBBBRRBBBRRRRBRRRRBRRRRRRRRRRRRRRRRRRRRRRBRRRRRRRRRBBBRRRRRRRBBBBBRRRRRBBBBBBBRRRBBBBBBBBBRBBBBB";
    char heartE[] =    "BBBBBBBBBBBBBBBBBBBBBBBBRRBBBRRBBBRBBRBRBBRBRBBBBRBBBBRBBBBBBBBBRBRBBBBBBBRBBBRBBBBBRBBBBBRBBBRBBBBBBBRBRBBBBBBBBBRBBBBB";
    for(int i = 0; i < health; i++) {
        draw_img(i*11, 0, heart);
        }
    for(int i = 0; i < maxHealth - health; i++) {
        draw_img((i+1)*-11+maxHealth*11, 0, heartE);
        }
}

void draw_border()
{
    uLCD.filled_rectangle(0,     12, 127,  14, WHITE); // Top
    uLCD.filled_rectangle(0,    13,   2, 114, WHITE); // Left
    uLCD.filled_rectangle(0,   114, 127, 117, WHITE); // Bottom
    uLCD.filled_rectangle(124,  14, 127, 117, WHITE); // Right
}

void draw_npc(int u, int v) 
{
    //char npc[] = "BBBBBBBBBBB BBBBRRRBBBB BBBRYRYRBBB BBR3YRY3RBB BRYYYRYYYRB BRRRRRRRRRB BRYYYRYYYRB BBRYYYYYRBB BBBRYYYRBBB BBBBRRRBBBB BBBBBBBBBBB"   
    char npc[] ="BBBBBBBBBBBBBBBRRRBBBBBBBRYRYRBBBBBR3YRY3RBBBRYYYRYYYRBBRRRRRRRRRBBRYYYRYYYRBBBRYYYYYRBBBBBRYYYRBBBBBBBRRRBBBBBBBBBBBBBBB";
    draw_img(u, v, npc);   
}
void draw_sonar(int u , int v)
{
    //char sonar[] = "BBBBBBBBBBB BBBBBWBBBBB BBBBWLWBBBB BBBWLLLWBBB BBWLWLWLWBB BWLLLLLLLWB BBWLWLWLWBB BBBWLLLWBBB BBBBWLWBBBB BBBBBWBBBBB BBBBBBBBBBB"
    char sonar[] = "BBBBBBBBBBBBBBBBWBBBBBBBBBWLWBBBBBBBWLLLWBBBBBWLWLWLWBBBWLLLLLLLWBBBWLWLWLWBBBBBWLLLWBBBBBBBWLWBBBBBBBBBWBBBBBBBBBBBBBBBB";
    draw_img(u, v, sonar);      
}

void draw_chest(int u, int v)  
{
    //char chest[] =   "BBBBBBBBBBB BBBBBBBBBBB BBBDDDDDBBB BBDYYYYYDBB BDYYYYYYYDB BDDDDDDDDDB BDDDBYBDDDB BDDDBYBDDDB BDDDBBBDDDB BDDDDDDDDDB B555555555B"
    char chest[] =   "BBBBBBBBBBBBBBBBBBBBBBBBBDDDDDBBBBBDYYYYYDBBBDYYYYYYYDBBDDDDDDDDDBBDDDBYBDDDBBDDDBYBDDDBBDDDBBBDDDBBDDDDDDDDDBB555555555B";
    draw_img(u, v, chest);
}

void draw_spider(int u, int v)
{
    //char spider[] = "BBBBBBBBBBB BWBBWWWBBWBBWBWRBRWBWBBBWBWBWBWBBBBBWWWWWBBBBBBWRRRWBBB BBBWWWWWBBBBBWBWRWBWBB BWBBWRWBBWB BWBBWWWBBWB BBBBBBBBBBB   
   char spider[] = "BBBBBBBBBBB BWBBWWWBBWBBWBWRBRWBWBBBWBWBWBWBBBBBWWWWWBBBBBBWRRRWBBBBBBWWWWWBBBBBWBWRWBWBBBWBBWRWBBWBBWBBWWWBBWBBBBBBBBBBBB";  
    draw_img(u,v, spider);
}
